version: 0.0
os: linux
files:
  - source:  /
    # ec2 목적지
    destination: /home/wookim/flask_test/
hook:
  BeforeInstall:
      - location: /home/wookim/flask_test/unzip_shell.sh
        timeout: 300
        runas: root